### PR TITLE
Do not apply a refactoring if it drops comments

### LINKED ISSUE #93: Apply hint: use guards remove comments above
Hi, [using hls-hlint-plugin an user](https://github.com/haskell/haskell-language-server/issues/597) has detected that apply "use guards" remove comments above the inserted guard:

```shell
PS D:\dev\ws\haskell\cabal-test> cat .\src\HlintTests.hs
module HlintTests where

bar :: Maybe Int -> [Int] -> String
bar x y =
  -- this is a comment
  if isJust x then "1"
  else if Prelude.null y then "2"
  else "3"

PS D:\dev\ws\haskell\cabal-test> hlint .\src\HlintTests.hs --refactor
module HlintTests where

bar :: Maybe Int -> [Int] -> String
bar x y
  | isJust x = "1"
  | Prelude.null y = "2"
  | otherwise = "3"

PS D:\dev\ws\haskell\cabal-test> hlint --version
HLint v3.2.1, (C) Neil Mitchell 2006-2020
PS D:\dev\ws\haskell\cabal-test> refactor --version
v0.8.2.
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by zliu41**
As a result, we no longer filter overlapping hints out before applying them; instead, we filter them out as we go. Because if refactoring A overlaps with refactoring B, but A isn't applied due to dropping comments, then B can still be applied.

Fixes #93

### CODE REVIEW

**Comment by jneira** [comment]
Hi @zliu41 , not sure if this is related with a [broken test case](https://github.com/haskell/haskell-language-server/runs/1693247524?check_suite_focus=true) in hls using apply-refact [head](58760460d31e89df82edf1d9048d95e707a39b69):

```
apply-refact preserve regular comments:                                                           FAIL (1.64s)
  test/functional/FunctionalCodeAction.hs:188:
  expected: "-- comment before header\nmodule ApplyRefact6 where\n\n{-# standalone annotation #-}\n\n-- standalone comment\n\n-- | haddock comment\nf = {- inline comment -} 1 -- ending comment\n\n-- final comment\n"
  but got: "-- comment before header\nmodule ApplyRefact6 where\n\n{-# standalone annotation #-}\n\n-- standalone comment\n\n-- | haddock comment\nf = {- inline comment -} (1) -- ending comment\n\n-- final comment\n"
```

The hint is not applied but in [previous runs](https://github.com/haskell/haskell-language-server/runs/1686429124?check_suite_focus=true) using 4fbd3a3 with the same hls code, the test was succesful (so it applied the hint and preserved comments)

The code for ghc-8.6.5 uses the old `applyRefactoring`

I am gonna use 4fbd3a3 again to see if the test case is green again and will confirm here the result

**Comment by jneira** [comment]
Well i did not test a inline comment *inside* the code being refactores:

`({- inline comment inside refactored code -}1)`

So maybe the refactoring would remove it (i will add that case in my test suite). If that is the case, maybe the code could detect if the comment is inside the source span being refactored and no outside

**Comment by jneira** [comment]
Mmm reviewing the test cases here i think `{- inline comment -}` is being attached to `(` and, as the refactor will drop `(`, it preserves the comment, not applying the hint.

Not sure if that is which i would expect, i guess the code is being conservative, as the comment could refer the tokens being removed in some way, or is there another reason?

**Comment by jneira** [comment]
After use 4fbd3a3 with https://github.com/haskell/haskell-language-server/pull/635/commits/714443080a8f1526e96b670491a622a4594b107b the test is succesful again: https://github.com/haskell/haskell-language-server/pull/635/checks?check_run_id=1693884153

I'am gonna add a comment inside refactored code in the test case for completeness

**Comment by jneira** [comment]
The test case has failed with

```
         test/functional/FunctionalCodeAction.hs:188:
        expected: "-- comment before header\nmodule ApplyRefact6 where\n\n{-# standalone annotation #-}\n\n-- standalone comment\n\n-- | haddock comment\nf = {- inline comment -} {- inline comment inside refactored code -}1 -- ending comment\n\n-- final comment\n"
         but got: "-- comment before header\nmodule ApplyRefact6 where\n\n{-# standalone annotation #-}\n\n-- standalone comment\n\n-- | haddock comment\nf = {- inline comment -}{- inline comment inside refactored code -} 1 -- ending comment\n\n-- final comment\n"
```
So 4fbd3a3 preserve comments inside the refactored code but it removed one existent whitespace before

The file being tested is 

```haskell
-- comment before header
module ApplyRefact6 where

{-# standalone annotation #-}

-- standalone comment

-- | haddock comment
f = {- inline comment -} ({- inline comment inside refactored code -}1) -- ending comment

-- final comment
```

**Comment by zliu41** [comment]
@jneira Thanks for reporting these problems!  In the `{- comment -} (1)` case, the refactoring is supposed to be performed since it wouldn't drop the comment. So this is a bug. What happened is that when a comment is attached to the entire hint, it is always preserved. In this case, the comment is attached to the `HsPar`, and the `HsPar` is the entire hint. And so the comment is preserved. This is a behavior I wasn't aware of. The fix should be easy; I'll try to fix it tomorrow.

I'll take a closer look at the `({- comment -} 1)` case and see how to make the whitespaces right.

**Comment by zliu41** [comment]
@jneira I have fixed the `{- comment -} (1)` case. Will make a release tomorrow.

The `({- comment -}1)` case is trickier. Here the comment has a `DeltaPos` of (0, 0), meaning it appears immediately after the previous object, `(`. So when the `(` is removed, we'd need to update its `DeltaPos` appropriately, but I haven't found a clean and uniform way to do that. This won't be fixed before the release, and I opened #105 for tracking.

**Pull request merged**
