### PR TITLE
GHC 9.2.1 support

### PR DESCRIPTION
**Pull request by alanz**
Focused on getting it to compile, by commenting out operational parts
lavishly.

The assumption is GHC 9.2.1 only, a new version, as the concept of
separate annotations is now gone.

These will be brought back while working through tests.

### CODE REVIEW

**Comment by alanz** [comment]
With a modified ghc-exactprint at version 1.5.0 this branch now compiles and passes tests for GHC 9.2.1

**Comment by alanz** [comment]
Should I expect hlint to pass?

**Comment by zliu41** [comment]
@alanz No need to fix HLint for now. Besides HLint there's some other cleanup we can do but I'm happy to do them after merging this.

**Comment by LeventErkok** [comment]
@alanz @zliu41 ping! can this be merged now?

**Comment by zliu41** [comment]
> can this be merged now?

@alanz What do you think?

It appears so, but I'm not very up to date wrt GHC 9.2 stuff and I'm not sure whether Alan thinks it's ready to merge. I'll merge it if Alan doesn't respond in the next few days.

**Comment by alanz** [comment]
I think it is ready to be merged. And has been for ages.

**Pull request merged**
