### PR TITLE
Do not remove comma from arithmetic sequences

### PR DESCRIPTION
**Pull request by zliu41**
Currently it refactors
```haskell
x = f $ [1,2..5]
```
into
```haskell
x = f [12..5]
```

The comma in an arithmetic sequence should not be removed.

### CODE REVIEW

**Comment by zliu41** [comment]
@mpickering ping. Could you take a look at this? This bug can be dangerous because it silently makes the code incorrect.

**Comment by mpickering** [comment]
@zliu41 Would you like to maintain this library? I am only hesistant to merge this patch as I no longer remember how the library works and am cautious to not break it.

**Comment by ndmitchell** [comment]
FWIW, @zliu41 has been doing all the refactoring stuff on the HLint side, and has done an awesome job. Since he de-facto owns the HLint side already, having him own the whole pipeline would be great from my perspective, if he wants to.

**Comment by zliu41** [comment]
@mpickering I'd be happy to maintain the library.

**Comment by zliu41** [comment]
Tested on both apply-refact's and HLint's test suite. Should be safe to merge.

**Pull request merged**
