### PR TITLE
Drop the GHC 8 support

### PR DESCRIPTION
**Pull request by wavewave**
Supporting GHC 8 is too much burden, especially due to the big changes in GHC API.
Currently, the master branch is only buildable on GHC 9.4 anyway. I remove all the GHC 8 related code. 
After this, we can set up 9.2 support better if we want (with proper CI support as well).

### CODE REVIEW

**Comment by wavewave** [comment]
GHC 9.2 build fix is here: https://github.com/wavewave/apply-refact/pull/1
will be rebased after this is merged onto master here.

**Comment by zliu41** [comment]
@wavewave could you rebase so that CI runs properly.

**Comment by wavewave** [comment]
now rebased. Btw, the CI check on pull requests does not seem to have been configured. Am I right?

**Comment by wavewave** [comment]
@zliu41 : I need your approval ;-) 
Screen Shot 2022-12-16 at 11 23 31 AM

**Comment by zliu41** [comment]
Thanks!

**Pull request merged**
